apiVersion: v1alpha1
kind: Config
logger:
  level: info
  enableCaller: false
  enableTimestamp: true
  timeFormat: timeonly
deploy:
  deployments:
    - name: secrets
      kubectl:
        secrets:
          generic:
          - &storageSecret
            name: storage-secret
            namespace: secrets
            literal:
            - key: hostname
              value: localhost
            - key: port
              value: 7777
            - key: username
              value: service-account
            - key: password
          - name: aws-creds
            namespace: secrets
            literal:
            - key: AWS_ACCESS_KEY
              value: 7777777
            - key: AWS_SECRET_KEY
          dockerRegistry:
          - name: custom-image-pull-secret
            namespace: custom
            registry: private-container-registry
    - name: more-secrets
      kubectl:
        secrets:
          generic:
          - <<: *storageSecret
            namespace: test
          - name: aws-creds
            namespace: security
            literal:
            - key: AWS_ACCESS_KEY
              value: 7777777
            - key: AWS_SECRET_KEY
    - name: private-helm-repos
      helm:
        repositories:
        - name: private
          url: https://private.helm.repo
          private: true
          init: true

