apiVersion: v1alpha3
kind: Config
logger:
  level: info
  enableCaller: false
  enableTimestamp: false
  timeFormat: timeonly
deploy:
  profiles:
    - name: observability
      aliases:
      - telemetry
      description:
        deploy: "deploy an observability stack to the cluster"
        delete: "delete an observability stack from the cluster"
      items:
      - istio
      - jaeger
      - loki
      - prometheus-operator
    - name: logging
      description:
        deploy: "deploy a logging stack to the cluster"
        delete: "delete a logging stack from the cluster"
      items:
      - istio
      - loki
    - name: metrics
      description:
        deploy: "deploy a metrics stack to the cluster"
        delete: "delete a metrics stack from the cluster"
      items:
      - istio
      - prometheus-operator
  deployments:
    - name: istio
      description:
        deploy: deploy Istio to your k8s cluster
        delete: delete Istio from your k8s cluster
      kubectl:
        manifests:
        - namespace: istio-system
          priority: 2
          paths:
          - manifests/istio-gateway.yaml
      helm:
        repositories:
        - name: istio
          init: true
          url: https://istio-release.storage.googleapis.com/charts
        charts:
        - priority: 1
          chartName: base
          releaseName: istio-base
          namespace: istio-system
          repoName: istio
          version: 1.14.1
          values:
          - values/istio-base-values.yaml
          installArgs:
          - --create-namespace
        - priority: 1
          chartName: istiod
          releaseName: istiod
          namespace: istio-system
          repoName: istio
          version: 1.14.1
          values:
          - values/istiod-values.yaml
          installArgs:
          - --create-namespace
        - priority: 2
          chartName: gateway
          releaseName: istio-ingressgateway
          namespace: istio-system
          repoName: istio
          version: 1.14.1
          values:
          - values/istio-gateway-values.yaml
          setValues:
          - service.externalIPs[0]=CHANGE_ME # Set this to your node InternalIP (minikube ip, or describe your node if you're not using minikube)
          installArgs:
          - --create-namespace
    - name: jaeger
      description:
        deploy: deploy Jaeger to your k8s cluster
        delete: delete Jaeger from your k8s cluster
      kubectl:
        manifests:
        - namespace: tracing
          priority: 3
          paths:
          - manifests/jaeger-virtual-service.yaml
      helm:
        repositories:
        - name: jaegertracing
          init: true
          url: https://jaegertracing.github.io/helm-charts
        charts:
        - priority: 3
          chartName: jaeger
          releaseName: jaeger
          namespace: tracing
          repoName: jaegertracing
          version: 0.57.1
          values:
          - values/jaeger-values.yaml
          installArgs:
          - --create-namespace
    - name: loki
      description:
        deploy: deploy Loki to your k8s cluster
        delete: delete Loki from your k8s cluster
      helm:
        repositories:
        - name: grafana
          init: true
          url: https://grafana.github.io/helm-charts
        charts:
        - priority: 3
          chartName: loki-stack
          releaseName: loki
          namespace: logging
          repoName: grafana
          version: 2.6.5
          installArgs:
          - --create-namespace
    - name: prometheus-operator
      aliases:
      - prom-op
      description:
        deploy: deploy Prometheus Operator to your k8s cluster
        delete: delete Prometheus Operator from your k8s cluster
      kubectl:
        manifests:
        - namespace: monitoring
          priority: 2
          paths:
          - manifests/grafana-virtual-service.yaml
      helm:
        repositories:
        - name: prometheus-community
          init: true
          url: https://prometheus-community.github.io/helm-charts
        charts:
        - priority: 2
          chartName: kube-prometheus-stack
          releaseName: prometheus-operator
          namespace: monitoring
          repoName: prometheus-community
          version: 36.0.2
          values:
          - values/prometheus-operator-values.yaml
          installArgs:
          - --create-namespace
